
import { SessionProvider } from '../components/SessionProvider'
import './styles/globals.css'



export const metadata = {
  title: 'StoryPost',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,

}: {
  children: React.ReactNode,

}) {

  return (
    <html lang="en">
      <body>

        <SessionProvider>
          {children}
        </SessionProvider>

      </body>
    </html>
  )
}




