
import Login from './components/Login'
import { SessionProvider } from './components/SessionProvider'
import { userService } from './services/userService'
import './styles/globals.css'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,

}: {
  children: React.ReactNode,

}) {

  return (
    <html lang="en">
      <body>

        <SessionProvider>
          {children}
        </SessionProvider>

      </body>
    </html>
  )
}




